booking/urls.py
from django.conf.urls import url
from . import views

app_name = 'booking'
urlpatterns = [
    #url(r'^(?P<car_id>[0-9]+)/ledighet/$', views.car_availability, name='car_availability'),
    url(r'^reserver/(?P<car_id>[0-9]+)/$', views.booking_schema, name='reservation_schema'),
    url(r'^pdf/(?P<reservation_id>[0-9]+)/(?P<car_id>[0-9]+)/$', views.download_pdf, name='pdf'),
]

cars/urls.py
from django.conf.urls import url
from . import views

app_name = 'cars'
urlpatterns = [
    url(r'^biler/$', views.car_list, name='car_list'),
    url(r'^bil/(?P<car_id>[0-9]+)/$', views.specific_car, name='car_availability'),
]

rustavrak/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns

from frontpage.views import index
urlpatterns = [
    url(r'^$', index),
    url(r'^', include('cars.urls', namespace='cars')),
    url(r'^', include('booking.urls')),
    url(r'^control_panel/', include('control_panel.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

booking/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.core.validators import RegexValidator
from django.db import models

from cars.models import Car

# Create your models here.
@python_2_unicode_compatible
class Dates_Reserved(models.Model):
    car = models.ForeignKey(Car, related_name='reserved_car', on_delete=models.CASCADE)

    initial_date = models.DateField('Hente Dato')
    final_date = models.DateField('Leverings Dato')

    def __str__(self):
        return str(self.id) + " " + self.car.brand + " " + self.car.model + ": Fra " + str(self.initial_date) + " Til: " + str(self.final_date)

    class Meta:
        verbose_name = 'dato_reservasjon'
        verbose_name_plural = 'dato_reservasjoner'


@python_2_unicode_compatible
class Customer(models.Model):
    email = models.EmailField('Epost Adresse', primary_key=True, max_length=100)

    # Customer Information
    first_name = models.CharField('Fornavn', max_length=100)
    last_name = models.CharField('Etternavn', max_length=100)
    phone_number = models.CharField('Telefonnummer', max_length=12, validators=[RegexValidator(r'^\d{1,10}$')])

    # Reservation counter
    num_orders = models.IntegerField('Antall bestilinger', default=0)

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    class Meta:
        verbose_name = 'Kunde'
        verbose_name_plural = 'Kunder'


@python_2_unicode_compatible
class Reservation(models.Model):
    #dates_reserved = models.ForeignKey(Dates_Reserved, related_name='booking', on_delete=models.CASCADE)
    car = models.ForeignKey(Car, verbose_name="Bil", related_name='Bil', on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, verbose_name='Kunde', related_name='Kunde', on_delete=models.CASCADE)

    # Additional information
    misc_info = models.CharField('Ekstra informasjon', max_length=255, blank=True, null=True)

    # Reservation Status
    status = models.PositiveSmallIntegerField('Ordrestatus',
                                              choices={(1, 'Ny'), (2, 'Godkjent'), (3, 'Avslått')})

    initial_date = models.DateField('Hente Dato')
    final_date = models.DateField('Leverings Dato')

    date_made = models.DateField('Bestilligns dato', auto_now_add=True)


    def __str__(self):
        return self.car.brand + " " + self.car.model + ". " + str(self.date_made)


    class Meta:
        verbose_name = 'Reservasjon'
        verbose_name_plural = 'Reservasjoner'

booking/forms.py
    # -*- coding: utf-8 -*-
from django import forms
from django.core.validators import RegexValidator
import datetime


class BookingForm(forms.Form):
    #Essential information for the Booking.
    initial_date = forms.DateField()
    final_date = forms.DateField()



class BookingRegistrationForm(forms.Form):
    first_name = forms.CharField(label='Fornavn', max_length=100)
    last_name = forms.CharField(label='Etternavn', max_length=100)

    email = forms.EmailField(label='Epost adresse', max_length=100)
    phone_number = forms.CharField(max_length=12, validators=[RegexValidator(r'^\d{1,10}$')])

    misc_info = forms.CharField(label='Ekstra informasjon (Maks 255 Karakterer)', max_length=255, required=False)

booking/views.py
# -*- coding: utf-8 -*-


from django.shortcuts import render, HttpResponse
from django.shortcuts import get_object_or_404, redirect



from .forms import BookingRegistrationForm
from .models import Car, Dates_Reserved, Reservation, Customer

from send_django_mail import send_mail_django
from frontpage.views import index
from data_functions import price_calculator
from reportlab.pdfgen import canvas


import logging


def booking_schema(request, car_id):

    if 'current_booking_id' in request.session:
        current_booking_id = request.session['current_booking_id']
    else:
        # Session has no booking ID, return to the frontpage
        return redirect(index)

    if request.method == 'POST':
        booking_scheme_form = BookingRegistrationForm(request.POST)

        if booking_scheme_form.is_valid():

            # Clean the information from the POST request
            first_name = booking_scheme_form.cleaned_data['first_name']
            last_name = booking_scheme_form.cleaned_data['last_name']
            email = booking_scheme_form.cleaned_data['email']
            phone_number = booking_scheme_form.cleaned_data['phone_number']
            misc_info = booking_scheme_form.cleaned_data['misc_info']

            current_car = get_object_or_404(Car, id=car_id)
            current_booking = get_object_or_404(Dates_Reserved, id=current_booking_id)

            customer, created = Customer.objects.update_or_create(pk=email,
                                                               defaults={'first_name': first_name,
                                                                         'last_name': last_name,
                                                                         'phone_number': phone_number})

            # Increment orders by this user
            customer.num_orders += 1
            customer.save()


            new_reservation, created = Reservation.objects.update_or_create(car_id=car_id,
                                                                   customer=customer,
                                                                   initial_date=current_booking.initial_date,
                                                                   defaults={
                                                                       'misc_info': misc_info,
                                                                       'status': 1, #Status 2 is defined as approved
                                                                       #'initial_date': current_booking.initial_date,
                                                                       'final_date': current_booking.final_date,
                                                                   })

            if created:
                logging.info("New Entry saved, ID: %s, by user %s" % (str(new_reservation.id), customer.email))
            else:
                logging.warning("User has updated an entry. Info: Booking Nr. %s, Customers email: %s" % (str(new_reservation.id), customer.email))


            # TODO: Something has to be done with this table. Maybe figure out some alternative sollution.
            # Deletes the booking dates from the database.
            #current_booking.delete()

            # Calculate
            number_of_days = (new_reservation.final_date - new_reservation.initial_date).days
            price = price_calculator(number_of_days, current_car.price)
            km_included = number_of_days * 50

            # Run the function that handles the sending of receipt.
            send_mail_django(new_reservation, current_booking, current_car, price)
            print(str(customer))
            context = {
                'car': current_car,
                'booking': current_booking,
                'customer': customer,
                'filled_form': new_reservation,
                'price': price,
                'km_included': km_included,
            }

            #Redirect the user to the final page, reciept is shown etc.
            return render(request, 'booking/booking_receipt.html', context)



        # User posted a form which was not valid.
        else:
            error_message = "Feil med gitt informasjon, prøv igjen. "

            form = booking_scheme_form
            car = get_object_or_404(Car, id=car_id)
            booking = get_object_or_404(Dates_Reserved, id=current_booking_id)

            number_of_days = (booking.final_date - booking.initial_date).days
            price = price_calculator(number_of_days, car.price)
            km_included = number_of_days * 50

            context = {
                'car': car,
                'booking': booking,
                'days': number_of_days,
                'price': price,
                'form': form,
                'error_message': error_message,
                'km_included': km_included
            }

            return render(request, 'booking/booking_form.html', context)

    # GET request.
    else:
        car = get_object_or_404(Car, id=car_id)
        booking = get_object_or_404(Dates_Reserved, id=current_booking_id)

        number_of_days = (booking.final_date - booking.initial_date).days
        price = price_calculator(number_of_days, car.price)
        km_included = number_of_days*50


        context = {
            'car': car,
            'booking': booking,
            'days': number_of_days,
            'price': price,
            'km_included': km_included
        }

        return render(request, 'booking/booking_form.html', context)



def download_pdf(request, reservation_id, car_id):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="Rusta_vrak_reservasjon.pdf"'

    reservation = get_object_or_404(Reservation, id=reservation_id)
    if reservation.car_id is not int(car_id):
        return redirect('/')

    reservation_nr = str(reservation.id)
    initial_date = reservation.initial_date.strftime('%d.%m.%Y')
    final_date = reservation.final_date.strftime('%d.%m.%Y')
    bil = str(reservation.car.brand.encode('utf8') + ' ' + reservation.car.model.encode('utf8'))
    car_fuel = str(reservation.car.fuel_type.encode('utf8'))
    car_seats = str(reservation.car.seats)
    car_transmission = str(reservation.car.transmission.encode('utf8'))
    days = (reservation.final_date - reservation.initial_date).days
    calculated_price = price_calculator(days, reservation.car.price)
    pris = str(calculated_price)
    fornavn  = reservation.customer.first_name
    etternavn = reservation.customer.last_name
    kunde = str(fornavn + ' ' + etternavn)

    epost = str(reservation.customer.email)
    tlf = str(reservation.customer.phone_number)


    p = canvas.Canvas(response)
    p.setLineWidth(.5)
    p.setFont('Helvetica', 24)
    p.drawString(60, 780, 'Rusta Vrak Bilutleige')
    p.drawString(60, 750, 'Ordre Bekreftelse')
    #p.setLineWidth(.3)
    #p.setFont('Helvetica', 18)
    #p.drawString(100, 720, 'Bestilling')
    #p.line(20, 710, 580, 710)
    p.setLineWidth(.5)

    p.line(20, 705, 580, 705)
    p.setFont('Helvetica', 16)
    p.drawString(60, 690, 'Reservasjonen')
    p.setFont('Helvetica', 13)
    p.drawString(80, 675, 'Reservasjon Nr')
    p.setLineWidth(.3)
    p.drawString(350, 675, reservation_nr)
    p.drawString(80, 655, 'Hente Dato: ')
    p.drawString(350, 655, initial_date)
    p.drawString(80, 640, 'Leveres Dato:')
    p.drawString(350, 640, final_date)

    p.line(20, 620, 580, 620)

    p.setFont('Helvetica', 16)
    p.drawString(60, 600, 'Bilen')
    p.setFont('Helvetica', 13)
    p.drawString(80, 585, bil)
    #p.setLineWidth(.3)
    p.drawString(350, 570, car_fuel)
    p.drawString(80, 570, 'Drivstoff')

    p.drawString(350, 555, car_seats)
    p.drawString(80, 555, 'Antall Seter')


    p.drawString(80, 540, 'Girkasse')
    p.drawString(350, 540, car_transmission)





    p.line(20, 530, 580, 530)
    p.setFont('Helvetica', 16)
    p.drawString(60, 500, 'Kunde Opplysninger')

    p.setFont('Helvetica', 13)
    p.drawString(80, 480, 'Navn')
    p.drawString(350, 480, kunde)

    p.drawString(80, 465, 'Epost')
    p.drawString(350, 465, epost)

    p.drawString(80, 450, 'Telefon Nummer')
    p.drawString(350, 450, tlf)




    p.line(20, 445, 580, 445)
    p.setFont('Helvetica', 16)



    p.drawString(60, 75, 'Kontakt Informasjon')
    p.setFont('Helvetica', 14)
    p.drawString(80, 60, 'Epost adresse: rusta.vrak@gmail.com')
    p.drawString(80, 45, 'Telefon +47 400 49 489')



    p.showPage()
    p.save()
    return response

booking/templates/booking/booking_form.html
{% extends 'base.html' %}


{% block pageBasedStyle %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static "booking/css/bookingstyle.css" %}">
<link rel="stylesheet" href="{% static "booking/css/booking_form_style.css" %}">
{% endblock pageBasedStyle %}


{% block Content %}
<div class="container" id="form_container">

    <div class="row">


        <div class="col-md-offset-2 col-md-9">
        <h1>Kontakt Informasjon</h1>

        <p>For å fulføre reservasjonen, vennligst fyll ut det følgende skjema. Husk å dobbelsjekk informasjon av reservasjonen før du går videre.</p>
        </div>
        <div class="col-md-offset-3 col-md-6">

            <form method="post" >{% csrf_token %}
                <div class="form-group">
                    <label for="email">Epost adresse</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Epost">
                        {{ form.email.errors }}
                </div>
                <div class="form-group">
                    <label for="first_name">Fornavn</label>
                    <input type="text" class="form-control" id="first_name" name="first_name" placeholder="Fornavn">
                        {{ form.first_name.errors }}
                </div>
                <div class="form-group">
                    <label for="last_name">Etternavn</label>
                    <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Fornavn">
                        {{ form.last_name.errors }}
                </div>

                <div class="form-group">
                    <label for="phone_number">Telefonnummer</label>
                    <input type="tel" class="form-control" id="phone_number" name="phone_number" placeholder="Telefonnummer">
                     {{ form.phone_number.errors }}
                </div>


                <div class="form-group">
                    <label for="misc_info">Annen Informasjon</label>
                    <textarea class="form-control" id="misc_info" name="misc_info" rows="3"></textarea>
                </div>

                <button type="submit" class="btn">Fullfør bestilling</button>
            </form>
        </div>

        <div class="col-md-offset-1 col-md-10">
                <h1>Informasjon</h1>
                <div id="car_info_table">
                    <h3>Reservasjonen</h3>
                        <table class="table">
                            <tbody>
                              <tr>
                                <td>Hente Dato</td>
                                <td>{{ booking.initial_date }}</td>
                              </tr>
                              <tr>
                                <td>Leverers Dato</td>
                                <td>{{ booking.final_date }}</td>
                              </tr>
                              <tr>
                                <td>Antall Dager</td>
                                <td> {{ days }}</td>
                              </tr>
                              <tr id="total">
                                <td><b>Total pris</b></td>
                                <td><b>{{ price }}</b></td>
                              </tr>

                            </tbody>
                        </table>

                <!-- Table Div END -->
                </div>
                <div id="car_info_table">
                    <h3>{{ car.brand }} {{ car.model }} </h3>
                        <table class="table">
                            <tbody>
                              <tr>
                                <td>Girkasse</td>
                                <td>{{ car.transmission }}</td>
                              </tr>
                              <tr>
                                <td>Drivstoff</td>
                                <td>{{ car.fuel_type }}</td>
                              </tr>
                              <tr>
                                <td>Seter</td>
                                <td>{{ car.seats }}</td>
                              </tr>

                            {% if car.year %}
                              <tr>
                                <td>År</td>
                                <td>{{ car.year }}</td>
                              </tr>

                            {% endif %}

                            {% if car.extra_accessories %}
                              <tr>
                                <td>Tilbehør</td>
                                <td>{{ car.extra_accessories }}</td>
                              </tr>
                            {% endif %}
                              <tr>
                                <td>Gratis inkl. kjørelengde</td>
                                <td>{{ km_included }}km</td>
                              </tr>

                              <tr>
                                <td>Pris pr Km. (Dersom gratis inkl. lengde overstiges)</td>
                                <td> 1.00 kr</td>
                              </tr>

                            </tbody>
                        </table>

                <!-- Table Div END -->
                </div>
        </div>

    </div>

</div>

{% endblock Content %}

booking/templates/booking/booking_receipt.html
{% extends 'base.html' %}



{% block pageBasedStyle %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static "booking/css/receipt_style.css" %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
{% endblock pageBasedStyle %}


{% block Content %}
<div class="container">
    <div class="jumbotron" style="color: black;">
        <h2>Reservasjon er registrert i vårt system.</h2>
        <p style="font-size: large">En e-post med informasjon om reservasjonen er sendt til din adresse. Husk å sjekke spam/søppelpost dersom den ikke spretter opp. <br>
            <b>Merk:</b> Reservasjonen må bekreftes av oss før bestillingen er fullført. Vi vil ta kontakt.</p>

        <div style="padding-top: 20px;">
            <h3>Reservasjonsinformasjon</h3>
            <p>
            <table class="table">
             <tbody>
                <tr>
                    <td>Reservasjon Nr.</td>
                    <td>{{ filled_form.id }}</td>
                </tr>
                <tr>
                    <td>Bil</td>
                    <td>{{ car.brand }} {{ car.model }}, {{ car.seats }} seter, {{ car.fuel_type }}</td>
                </tr>
                <tr>
                    <td>Hentes Dato</td>
                    <td>{{ booking.initial_date|date:'d.m.Y' }}</td>
                </tr>
                <tr>
                    <td>Levers Dato</td>
                    <td>{{ booking.final_date|date:'d.m.Y' }}</td>
                </tr>

                <tr>
                    <td>Gratis inkl. kjørelengde</td>
                    <td>{{ km_included }} Km</td>
                </tr>

                <tr>
                    <td>Pris</td>
                    <td>{{ price }}kr</td>
                </tr>
                {%   if filled_form.misc_info %}
                <tr>
                    <td>Ekstra Informasjon</td>
                    <td>"{{ filled_form.misc_info }}"</td>
                </tr>
                {% endif %}
                <tr>

                </tr>
                <tr>
                    <td><h4>Bestiller</h4></td>
                    <td></td>
                </tr>
                <tr>
                    <td>Navn</td>
                    <td>{{ customer.first_name }} {{ customer.last_name }}</td>
                </tr>
                <tr>
                    <td>Epost</td>
                    <td>{{ customer.email }}</td>
                </tr>
                <tr>
                    <td>Telefon</td>
                    <td>{{ customer.phone_number }}</td>
                </tr>
            </tbody>
            </table>
        </div>

         <a href="{% url 'booking:pdf' filled_form.id car.pk %}">
            <button type="button" class="btn"><i class="fa fa-download" aria-hidden="true" ></i> Last ned reservasjonsinformasjon som PDF</button>
        </a>
    </div>


</div>
{% endblock Content %}