cars/urls.py
from django.conf.urls import url
from . import views

app_name = 'cars'
urlpatterns = [
    url(r'^biler/$', views.car_list, name='car_list'),
    url(r'^bil/(?P<car_id>[0-9]+)/$', views.specific_car, name='car_availability'),
]

rustavrak/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns

from frontpage.views import index
urlpatterns = [
    url(r'^$', index),
    url(r'^', include('cars.urls', namespace='cars')),
    url(r'^', include('booking.urls')),
    url(r'^control_panel/', include('control_panel.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

cars/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.utils.encoding import python_2_unicode_compatible
from django.core.validators import RegexValidator

from django.db import models

# Need to support python 2
# Old Car Table.
@python_2_unicode_compatible
class Car(models.Model):
    car_type = models.PositiveSmallIntegerField('Kategori', choices=[(1, 'Personbil'), (2, 'Varebil'), (3, 'Kombibil')])
    #Misc information
    brand = models.CharField('Bilmerke', max_length=70)
    model = models.CharField('Biltype', max_length=70)
    year = models.PositiveSmallIntegerField(blank=True, null=True)
    seats = models.PositiveSmallIntegerField('Antall seter')
    fuel_type = models.CharField('Type drivstoff', choices=[('Diesel', 'Diesel'), ('Bensin', 'Bensin'), ('Hybrid', 'Hybrid'), ('Elbil', 'Elbil')], max_length=20)
    transmission = models.CharField('Gir', choices=[('Manuell', 'Manuell'), ('Automatgir', 'Automatgir')], default='Manuell', max_length=15)
    extra_accessories = models.CharField('Ekstra informasjon, splitt med komma (",")', blank=True, null=True, max_length=255)
    price = models.IntegerField('Dagspris leie', default=250)
    for_rent = models.BooleanField('Bilen klar for utleie.', default=True)
    license_plate = models.CharField('Skiltnummer', max_length=10, unique=True)


    def __str__(self):
        if self.license_plate:
            return "Skiltnr: " +  self.license_plate + " | " + self.brand + " " + self.model
        else:
            return "Skiltnr: Ikke Oppgitt |" +  self.brand + " " + self.model

    class Meta:
        verbose_name = 'Bil'
        verbose_name_plural = 'Biler'


@python_2_unicode_compatible
class CarImages(models.Model):
    car = models.OneToOneField(
        Car,
        on_delete=models.CASCADE,
        primary_key=True,
    )

    thumbnail = models.CharField('Lenke til mini bilde', max_length=50, default='')
    main_image = models.CharField('Lenke til hovedbilde', max_length=50, default='')
    gallery_images = models.CharField('Bilder til galleri. Splitt lenkene via komma ","', max_length=255, blank=True, null=True)

    def __str__(self):
        return self.car.brand + ' ' + self.car.model

    class Meta:
        verbose_name = 'Bil Bilder'
        verbose_name_plural = 'Bil Bilder'

cars/forms.py
    # -*- coding: utf-8 -*-
from django import forms
from django.core.validators import RegexValidator
import datetime




DATE_INPUT_FORMATS = [
    '%d.%m.%Y',  # '12.02.2017'
    '%d/%m/%Y',  # '12/02/2006'
]


class BookingForm(forms.Form):
    #Essential information for the Booking.
    initial_date = forms.DateField(input_formats=DATE_INPUT_FORMATS)
    final_date = forms.DateField(input_formats=DATE_INPUT_FORMATS)


class FilterForm(forms.Form):
    personal = forms.BooleanField(required=False)
    van = forms.BooleanField(required=False)
    combi_car = forms.BooleanField(required=False)

    seats = forms.IntegerField(max_value=12, required=False)


    transmission_manual = forms.BooleanField(required=False)
    transmission_auto = forms.BooleanField(required=False)

    fuel_gasoline = forms.BooleanField(required=False)
    fuel_diesel = forms.BooleanField(required=False)

    initial_date = forms.DateField(input_formats=DATE_INPUT_FORMATS, required=False)
    final_date = forms.DateField(input_formats=DATE_INPUT_FORMATS, required=False)

cars/views.py
# -*- coding: utf-8 -*-


from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect
from django.core.exceptions import ObjectDoesNotExist

from .forms import BookingForm, FilterForm
from .models import Car
from booking.models import Dates_Reserved, Reservation

from validation import validate_date, find_available_cars, validate_availability

import logging
import datetime

from booking.data_functions import generate_booked_dates


def car_list(request):
    if request.method == 'POST':
        # This method shall handle filtering of the objects AND searching for dates and availability.
        filtered_data = FilterForm(request.POST)
        if filtered_data.is_valid():
            # Initialize variables
            dates = False
            categories = ''
            searched_categories = ''
            car_types = []

            # Car type
            if filtered_data.cleaned_data['personal']:
                car_types.append(1)
                categories += 'Personbil, '
            if filtered_data.cleaned_data['van']:
                car_types.append(2)
                categories += 'Varebil, '
            if filtered_data.cleaned_data['combi_car']:
                car_types.append(3)
                categories += 'Kombinertbil, '

            if categories:
                categories = categories.strip(", ")

            if not car_types:
                car_types = [1, 2, 3]
                categories = 'Personbil, Varebil og Kombinertbil'

            # 0 is All seats
            seats = []
            # Specific number of seats
            if filtered_data.cleaned_data['seats'] > 0:
                seats.append(filtered_data.cleaned_data['seats'])
            else:
                # All seat combo's
                seats = [2, 3, 5, 7, 8, 9]


            transmission_types = []
            # Transmission
            if filtered_data.cleaned_data['transmission_auto']:
                transmission_types.append('Automatgir')
                searched_categories += 'Automat, '

            if filtered_data.cleaned_data['transmission_manual']:
                transmission_types.append('Manuell')
                searched_categories += 'Manuell, '

            if not transmission_types:
                transmission_types = ['Manuell', 'Automatgir']

            # Fuel
            fuel_types = []
            if filtered_data.cleaned_data['fuel_diesel']:
                fuel_types.append('Diesel')
                searched_categories += 'Diesel, '

            if filtered_data.cleaned_data['fuel_gasoline']:
                fuel_types.append('Bensin')
                searched_categories += 'Bensin, '

            if not fuel_types:
                fuel_types = ['Diesel', 'Bensin']

            cars = Car.objects.filter(car_type__in=car_types).filter(transmission__in=transmission_types).filter(fuel_type__in=fuel_types).filter(seats__in=seats).filter(for_rent=True)

            # Date Handler
            if filtered_data.cleaned_data['initial_date'] and filtered_data.cleaned_data['final_date']:
                initial_date = filtered_data.cleaned_data['initial_date']
                final_date = filtered_data.cleaned_data['final_date']

                validate = validate_date(initial_date, final_date)

                # If the validate does not return an error.
                if not validate['error']:
                    cars = find_available_cars(initial_date, final_date, cars)

                    dates = {
                        'initial_date': initial_date,
                        'final_date': final_date,
                    }

                else:
                    # User Entered non valid dates.
                    logging.error("Non Valid dates found, do redirect home. , %s" % validate['message'])
                    request.session['search_car_error_message'] = validate['message']

                    return redirect('/')

            context = {
                'cars': cars,
                'dates': dates,
                'categories': categories,
                'searched_categories': searched_categories
            }

            return render(request, 'cars/car_list.html', context)

        # Not valid POST request, redirect the user back to the start.
        else:
            logging.error("Invalid search form posted." + filtered_data.errors)
            request.session['search_car_error_message'] = "Feil oppstod ved henting av biler. Prøv igjen"

            return redirect('/')



    else:
        car_type = request.GET.get('type')

        if car_type:
            types = car_type.split(',')
            types = map(int, types)
        else:
            types = []

        # Initialize categories as an empty string.
        categories = ''
        if 1 in types:
            categories += 'Personbiler, '
        if 2 in types:
            categories += 'Varebiler, '
        if 3 in types:
            categories += 'Kombinertbiler, '

        # Remove the last comma and space.
        categories = categories.strip(", ")


        # IF not any type(s) given, show the user them all.
        if not types:
            types = [1, 2, 3]
            categories = 'Personbiler, Varebiler og Kombinertbiler'




        cars = Car.objects.filter(car_type__in=types).filter(for_rent=True)

        context = {
            'categories': categories,
            'cars': cars,
        }

        return render(request, 'cars/car_list.html', context)


def specific_car(request, car_id):

    # Standard Abort function.
    def abort_function(current_car, error_message, current_car_reservations):
        calendar_data = generate_booked_dates(current_car_reservations)
        context = {
            'car': current_car,
            'dates': 'false',
            'warning': True,
            'message': error_message,
            'booked_dates_json': calendar_data,
        }
        return render(request, 'cars/spesific_car.html', context)

    # POST Request
    if request.method == 'POST':
        booking_form = BookingForm(request.POST)
        car = get_object_or_404(Car, id=car_id)

        if booking_form.is_valid():
            initial_date = booking_form.cleaned_data['initial_date']
            final_date = booking_form.cleaned_data['final_date']

            # Get all registered reservations for this car.
            existing_reservations = Reservation.objects.filter(car=car).exclude(final_date__lte=(datetime.date.today()))\
                .order_by('initial_date')

            # Run function to validate the two dates searched.
            validated_dates = validate_date(initial_date, final_date)
            if validated_dates['error']:
                return abort_function(car, validated_dates['message'], existing_reservations)

            # Checks the new dates against existing reservations and any reservation locks.
            validated_availability = validate_availability(initial_date, final_date, existing_reservations)
            if validated_availability['error']:
                return abort_function(car, validated_availability['message'], existing_reservations)

            # ============== Validation Passed ===============
            # Save the new record to the database.
            new_reservation = Dates_Reserved(car=car,
                                         initial_date=booking_form.cleaned_data['initial_date'],
                                         final_date=booking_form.cleaned_data['final_date']
                                         )
            new_reservation.save()
            request.session['current_booking_id'] = new_reservation.id
            return redirect('booking:reservation_schema', car_id=car.id)

        else:
            logging.debug("Non valid form posted.")
            existing_reservations = Reservation.objects.filter(car=car).exclude(
                final_date__lte=(datetime.date.today())) \
                .order_by('initial_date')
            message = "Informasjon mangler, prøv å fyll ut feltene på nytt. NB: Dato må være i format DD.MM.ÅÅÅÅ"

            return abort_function(car, message, existing_reservations)

    # GET request
    else:
        car = get_object_or_404(Car, id=car_id)

        images = image_generator(car)

        selected_dates = request.GET.values()

        if selected_dates:
            initial_date = selected_dates[1].encode('utf8')
            final_date = selected_dates[0].encode('utf8')

            dates = {
                'initial_date': initial_date,
                'final_date': final_date
            }
        else:
            dates = 'false'

        # Gather the information required by the Calendar
        existing_reservations = Reservation.objects.filter(car=car).exclude(
            final_date__lte=(datetime.date.today())) \
            .order_by('initial_date')

        booked_dates = generate_booked_dates(existing_reservations)

        context = {
            'car': car,
            'booked_dates_json': booked_dates,
            'images': images,
            'dates': dates
        }

        return render(request, 'cars/spesific_car.html', context)


def image_generator(car):
    """ Function to split up images for the gallery (if any)"""
    # Gallery images are stored as a string in the database
    # Simply split these strings by any ',' and store in a list.
    try:
        images_string = car.carimages.gallery_images.encode('utf-8')
    except ObjectDoesNotExist:
        return False

    # If the image string is not empty, split them up into a list.
    if images_string:
        images = images_string.split(',')
    else:
        images = False

    return images

cars/templates/cars/car_list.html
{% extends 'base.html' %}


{% block pageBasedStyle %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static "cars/css/car_list_style.css" %}"/>
<link rel="stylesheet" href="{% static "packages/lightbox/css/lightbox.css" %}"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
{% endblock pageBasedStyle %}


{% block Content %}
<div class="container" style="padding-bottom: 40px">
    {% if cars %}
    <div class="row">

        <div class="col-lg-6 col-md-6">
            <h3>Kategorier: {{ categories }}</h3>
            {% if dates %}
            <h4>Viser ledige biler fra : {{ dates.initial_date|date:'d.m.Y' }} til  {{ dates.final_date|date:'d.m.Y' }} </h4>
            {% endif %}
        </div>

        <div class="col-lg-12 col-md-12">
                <a href="#filter" data-toggle="collapse" style="color: white; font-size: large"><u>Instillinger for Søk</u></a>

                <div id="filter" class="collapse row">
                    <form method="post" action="" >{% csrf_token %}
                        <div class="col-md-2">
                            <h3>Biltype</h3>
                            <div class="checkbox">
                              <label><input type="checkbox" name="personal" id="personal" {% if "Personbil" in categories %} checked {% endif %}>Personbil</label>
                            </div>
                            <div class="checkbox">
                              <label><input type="checkbox" name="van" id="van" {% if "Varebil" in categories %} checked {% endif %}>Varebil</label>
                            </div>
                            <div class="checkbox">
                              <label><input type="checkbox" name="combi_car" id="combi_car" {% if "Kombinert" in categories %} checked {% endif %}>Kombinertbil</label>
                            </div>

                        </div>
                        <div class="col-md-2">



                        <h3>Drivstoff</h3>
                        <div class="checkbox">
                            <label class="checkbox-inline"><input type="checkbox" name="fuel_gasoline" id="fuel_gasoline" {% if "Bensin" in searched_categories %} checked {% endif %}>Bensin</label>
                        </div>
                        <div class="checkbox">
                            <label class="checkbox-inline"><input type="checkbox" id="fuel_diesel" name="fuel_diesel" {% if "Diesel" in searched_categories %} checked {% endif %}>Diesel</label>
                        </div>



                        </div>
                        <div class="col-md-3">

                        <h3>Gir</h3>
                        <div class="checkbox">
                            <label class="checkbox"><input type="checkbox" id="transmission_manual" name="transmission_manual" {% if "Manuell" in searched_categories %} checked {% endif %}>Manuell</label>
                        </div>
                        <div class="checkbox">
                            <label class="checkbox"><input type="checkbox" id="transmission_auto" name="transmission_auto" {% if "Automat" in searched_categories %} checked {% endif %}>Automat</label>
                        </div>


                        <label for="seats">Antall Seter</label>
                        <select id="seats" name="seats" style="color: black">
                          <option value="0">Alle</option>
                          <option value="3">2</option>
                          <option value="3">3</option>
                          <option value="5">5</option>
                          <option value="7">7</option>
                          <option value="9">9</option>
                        </select>

                        </div>



                        {% if dates %}
                        <input type="text" value="{{ dates.initial_date|date:'d.m.Y' }}" id="datepickerStart" name="initial_date" hidden>
                        <input type="text" value="{{ dates.final_date|date:'d.m.Y' }}" id="datepickerFinish" name="final_date" hidden>
                        {% endif %}
                         <div class="col-md-12">
                            <button type="submit" class="btn btn-lg" style="margin: 5px; background-color: #5C6B63;"><i class="fa fa-search" aria-hidden="true" ></i> Filter</button>
                         </div>
                    </form>
                <!-- End Collapse -->
                 </div>
        </div>
    {% for car in cars %}
        <div class="col-lg-12 col-md-12 car_tab" >
            <div class="col-md-4 col-sm-4">
                <div class="thumbnail car_images" style="border: none">

                    <a href="{{ car.carimages.main_image }}" id="{{ car.id }}" data-lightbox="image-{{ car.id }}" data-title="{{ car.brand }} {{ car.model }}"><img src="{{ car.carimages.thumbnail }}"></a>
                </div>

            </div>
            <div class="col-md-8 car_info">
                <h1> {{ car.brand }} {{ car.model }}</h1>
                <div class="col-md-6">
                     <p>{{ car.transmission }} <br>{{ car.fuel_type }}<br> Antall Seter: {{ car.seats }} <br> {% if car.year %} År: {{ car.year }} {% endif %}
                    {% if car.extra_accessories %}
                        Tilbehør: {{ car.extra_accessories }}
                    {% endif %}
                    </p>
                </div>
                <div class="col-md-6 car_price_info">
                    <p id="price_p"><b>Pris per dag:</b> {{ car.price }}</p>
                    <br>
                    <br>
                    {% if dates %}
                        <a class="btn" href="{% url 'cars:car_availability' car.id %}?fra={{ dates.initial_date|date:'d.m.Y' }}&til={{ dates.final_date|date:'d.m.Y'}}" style="vertical-align: middle;"  ><b>Se Detaljer </b></a>

                    {% else %}
                        <a class="btn" href="{% url 'cars:car_availability' car.id %}" style="vertical-align: middle;"  ><b>Se Tilgjengelighet</b></a>
                    {% endif %}

                </div>
            </div>
        </div>
        <h1></h1>
    {% endfor %}

    </div>
    {% else %}
        <h1>Ditt søk fant ingen biler i vår database. </h1>


    <input type="button" class="btn btn-default" value="Tilbake" onClick="javascript:history.go(-1);">
    {% endif %}
</div>


{% endblock Content %}


{% block siteSpesificJs %}
<script src="{% static "packages/lightbox/js/lightbox.js" %}"></script>

<script>
    lightbox.option({
      'showImageNumberLabel': false,
    })
</script>
{% endblock siteSpesificJs %}

cars/templates/cars/personal_cars.html
{% extends 'base.html' %}


{% block pageBasedStyle %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static "cars/css/personal_carsStyle.css" %}"/>
{% endblock pageBasedStyle %}


{% block Content %}
<div class="container">
    {% if personal_cars %}
    {% for car in personal_cars %}
        <div class="col-lg-12 car_tab" style="margin-top: 30px; margin-bottom: 30px;">
            <div class="col-md-4 ">
                <div class="thumbnail" style="border: none">
                    <img src="{{ car.main_image }}">
                </div>

            </div>
            <div class="col-md-8 car_info ">
                <h1> {{ car.brand }} {{ car.model }}</h1>
                 <p>Drivstoff: {{ car.fuel_type }}. Antall Seter: {{ car.seats }}. {% if car.year %} År: {{ car.year }} {% endif %}</p>
                <a class="btn btn-primary" href="{% url 'cars:car_availability' car.id %}">Se Ledighet </a>
            </div>
        </div>
        <h1></h1>
    {% endfor %}
    {% endif %}
</div>
{% endblock Content %}

cars/templates/cars/search_cars.html
{% extends 'base.html' %}

{% block pageBasedStyle %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static "cars/css/personal_carsStyle.css" %}"/>
{% endblock pageBasedStyle %}

{% block Content %}
<div class="container">
{% if cars %}
    {% for car in cars %}
        <div class="col-lg-12 car_tab" style="margin-top: 30px; margin-bottom: 30px;">
            <div class="col-md-4 ">
                <div class="thumbnail" style="border: none">
                    <img src="{{ car.carimages.main_image }}">
                </div>

            </div>
            <div class="col-md-8 car_info ">
                <h1> {{ car.brand }} {{ car.model }}</h1>
                 <p>Drivstoff: {{ car.fuel_type }}. Antall Seter: {{ car.seats }}. {% if car.year %} År: {{ car.year }} {% endif %}</p>
                <a class="btn btn-primary" href="{% url 'cars:car_availability' car.id %}">Se Ledighet </a>
            </div>
        </div>
        <h1></h1>
    {% endfor %}
{% else %}
<h1> Fant ingen ledige biler i den oppgitte periode</h1>
{% endif %}
</div>
{% endblock Content %}

cars/templates/cars/spesific_car.html
{% extends 'base.html' %}


{% block pageBasedStyle %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static "packages/lightbox/css/lightbox.css" %}"/>
<link rel="stylesheet" href="{% static "cars/css/spesific_carStyle.css" %}"/>
<link rel="stylesheet" href="{% static "packages/date-range-jquery/daterangepicker.min.css" %}">

{% endblock pageBasedStyle %}




<!-- TODO: Fix error message popup. Wrong dates, no dates, etc. etc.-->
{% block Content %}
<section id="car_images_section">
    <div class="container" id="car_image_container">
        <div class="row">
            <div class="col-md-12" style="text-align: center">
                <h1><b>{{ car.brand }} {{ car.model }}</b></h1>
            </div>
            <div class="col-md-offset-1 col-md-5">

                <a href="{{ car.carimages.main_image }}" id="{{ car.id }}" data-lightbox="image-{{ car.id }}" data-title="{{ car.brand }} {{ car.model }}">
                    <img src="{{ car.carimages.main_image }}" class="img-rounded img-responsive" alt="{{ car.brand }} {{ car.model }}" width="800" height="450">
                <!-- Main Image End -->
                </a>


                <!-- If the car contains multiple images -->
                {% if images %}
                <a href="#demo" data-toggle="collapse" style="color: white; font-size: large; margin-top: 5px;"><u>Flere Bilder</u></a>

                <div id="demo" class="collapse">

                    <div id="gallery_images_container">
                    {% for image in images %}
                    <a href="{{ image }}" id="{{ car.id }}" data-lightbox="image-{{ car.id }}" data-title="{{ car.brand }} {{ car.model }}" class="gallery_images">
                        <img src="{{ image }}" class="img-rounded " alt="{{ car.brand }} {{ car.model }}" width="101" height="78">
                    </a>
                    {% endfor %}
                    </div>
                <!-- End Collapse -->
                 </div>
                {% endif %}
            <!-- Image column end -->
            </div>

            <div class="col-md-6">


                <!-- Car Info Table -->
                <div id="car_info_table">

                <h3>Informasjon</h3>
                  <table class="table">
                    <tbody>
                      <tr>
                        <td>Girkasse</td>
                        <td>{{ car.transmission }}</td>
                      </tr>
                      <tr>
                        <td>Drivstoff</td>
                        <td>{{ car.fuel_type }}</td>
                      </tr>
                      <tr>
                        <td>Seter</td>
                        <td>{{ car.seats }}</td>
                      </tr>

                    {% if car.year %}
                      <tr>
                        <td>År</td>
                        <td>{{ car.year }}</td>
                      </tr>

                    {% endif %}

                    {% if car.extra_accessories %}
                      <tr>
                        <td>Tilbehør</td>
                        <td>{{ car.extra_accessories }}</td>
                      </tr>
                    {% endif %}
                      <tr>
                        <td>Gratis Inkludert. kjørelengde</td>
                        <td>50Km / Døgn</td>
                      </tr>

                      <tr>
                        <td>Pris pr Km.</td>
                        <td> 1.00 kr</td>
                      </tr>

                    </tbody>
                  </table>

                <!-- Table Div END -->
                </div>
                <div>
                    <p id="price_p"><b>Pris per dag:</b> {{ car.price }}</p>

                </div>
            <!-- Info column End -->
            </div>


        <!-- Row END -->
        </div>


        <div class="col-md-offset-1 col-md-10">
            <hr>
             <div class="range_calendar">
                        {% if warning %}
                            <div class="alert alert-danger" role="alert" style="font-size: large">
                                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                                <span class="sr-only">Error:</span>
                                <b>{{ message }}</b>
                            </div>
                        {% endif %}
                <h1><b>Legg til en ny reservasjon</b></h1>

             <p>Velg en ledig periode.</p>
             <div class="row">
                <div class="col-md-5 col-sm-12 col-xs-12 form-group has-feedback" style="max-width: 100%;">
                    <div id="date-range12-container" class="col-md-6" ></div>
                </div>

                <div class="col-md-offset-2 col-md-5 col-sm-12 col-xs-12 form-group has-feedback">
                     <form method="post" class="row" >{% csrf_token %}
                        <span id="date-range">
                            <div class="col-md-12 col-sm-12 col-xs-12 form-group has-feedback">
                                <label for="datepickerStart" class="control-label date-label">Hentes</label>
                                <input type="text" value='' class="form-control datefield" id="datepickerStart" name="initial_date">
                                <span class="glyphicon glyphicon-calendar form-control-feedback date_icon" ></span>
                            </div>

                            <div class="col-md-12 col-sm-12 col-xs-12 form-group has-feedback">
                                <label for="name" class="control-label date-label">Leveres</label>
                                <input type="text" value='' class="form-control datefield" id="datepickerFinish" name="final_date">
                                <span class="glyphicon glyphicon-calendar form-control-feedback date_icon" ></span>
                            </div>
                            <!-- <input size="20" id="datepickerStart" name="initial_date"> -->
                            <!-- <input size="20" id="datepickerFinish" name="final_date"> -->
                        </span>


                        {% if errors %}
                        {{ errors }}
                        {% endif %}
                        <div class="col-md-6 col-sm-6 col-xs-12" id="button_box">
                            <button type="submit" class="btn btn-lg">Gå Videre</button>
                        </div>
                    </form>
                </div>
              </div>
            </div>
        </div>

    <div class="col-md-offset-1 col-md-10">
        <hr>
        <h1><b>Detaljer for valgt periode</b></h1>
        <div class="col-md-offset-1 col-md-12">
            <h4 id="days_booked"></h4>
        </div>

        <div class="col-md-offset-1 col-md-12">
            <h4 id="total_price"></h4>
        </div>

        <div class="col-md-offset-1 col-md-12">
            <h4 id="free_length"></h4>
        </div>
    </div>

    <!-- Container END -->
    </div>




</section>

{% endblock Content %}



{% block testBlock %}

<script>

// Dates already booked, insertet as invalid dates in the date pickers
var booked_dates = {{ booked_dates_json | safe }};


// If searched by dates.
var dates = {{ dates | safe }};


var dp_start_date = $("#datepickerStart");
var dp_end_date = $("#datepickerFinish");

if(dates){
    dp_start_date.val(dates.initial_date);
    dp_end_date.val(dates.final_date);
}

dp_end_date.datepicker({
    minDate: 0,
    beforeShowDay: function(date){
        var string = jQuery.datepicker.formatDate('dd.mm.yy', date);
        return [ booked_dates.indexOf(string) == -1 ]
    }
});

dp_start_date.datepicker({
    minDate: 0,
    beforeShowDay: function(date){
        var string = jQuery.datepicker.formatDate('dd.mm.yy', date);
        return [ booked_dates.indexOf(string) == -1 ]
        }
    });

dp_start_date.on("input change", function (e) {
    var date = dp_start_date.datepicker('getDate');
    date.setDate(date.getDate()+1);
    dp_end_date.datepicker("option","minDate", date);
    });



</script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.16.0/moment.min.js" type="text/javascript"></script>
<script src="{% static "packages/date-range-jquery/jquery.daterangepicker.js" %}"></script>
<script src="{% static "cars/js/date-range-jquery_config.js" %}"></script>
<script src="{% static "cars/js/spesific_carJs.js" %}"></script>
<script src="{% static "packages/lightbox/js/lightbox.js" %}"></script>

{% endblock testBlock %}