cars/urls.py
from django.conf.urls import url
from . import views

app_name = 'cars'
urlpatterns = [
    url(r'^biler/$', views.car_list, name='car_list'),
    url(r'^bil/(?P<car_id>[0-9]+)/$', views.specific_car, name='car_availability'),
]

rustavrak/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns

from frontpage.views import index
urlpatterns = [
    url(r'^$', index),
    url(r'^', include('cars.urls', namespace='cars')),
    url(r'^', include('booking.urls')),
    url(r'^control_panel/', include('control_panel.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

rustavrak/templates/about.html
{% extends 'base.html' %}


{% block Content %}

<h1>Kontakt Informasjon</h1>
<p> Kontakt Oss <br>


Epost: rusta.vrak@gmail.com <br>

Telefon +47 400 49 489 <br>


</p>

{% endblock Content %}

rustavrak/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Rimelig bilutleige i Førde og Jølster. Vi tilbyr utleige av personbiler, varebiler og kombinert biler. Langstidsleie og kortidsleie. Jo lengre leie, jo billigere">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Rusta Vrak Bilutleige</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">


    <!-- Google Roboto Font -->
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">


    {% load staticfiles %}
    <link rel="shortcut icon" href="{%  static 'baseStyle/images/favicon.ico' %}">


    <link href="{% static "packages/JQuery/jquery-ui.css" %}" rel="stylesheet">
    <link rel='stylesheet' href='{% static "packages/fullcalendar/fullcalendar.css" %}' />
    <link rel="stylesheet" href="{% static "baseStyle/css/baseStyle.css" %}"/>




    {% block pageBasedStyle %}

    {% endblock pageBasedStyle %}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
  <body>
  <div id="wrap">

    <!-- Navigation bar -->
    <nav class="navbar navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Rusta Vrak Bilutleige</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Hjem</a></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    Biler <span class="caret"></span>
                </a>
              <ul class="dropdown-menu">
                    <li><a href="{% url 'cars:car_list'%}?type=1">Personbiler</a></li>
                    <li><a href="{% url 'cars:car_list'%}?type=2">Varebiler</a></li>
                    <li><a href="{% url 'cars:car_list'%}?type=3">Kombinertbiler</a></li>
                    <li><a href="{% url 'cars:car_list'%}?type=1,2,3">Alle</a></li>
              </ul>
            </li>
            <li><a href="/#policy" >Vilkår</a></li>
            <li><a href="/#contact">Kontakt</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>








          {% block Content %}

          {% endblock Content %}


        <div id="push"></div>
    </div>
    <footer class="footer">
        <div class="navbar-static-bottom">
          <div class="container">
              <div class="row">
                  <div class="col-md-6">
                    <h4>Kontakt</h4>
                    <ul style="list-style-type:none; padding-left:0;">
                        <li>Epost: rusta.vrak@gmail.com</li>
                        <li>Telefon: +47 400 49 489</li>
                    </ul>
                  </div>
                  <div class="col-md-6">
                    <h4>Lenker</h4>
                      <ul style="list-style-type:none; padding-left:0;">
                          <li><a href="#">Forside </a></li>
                          <li><a href="/#about">Om Oss </a></li>
                          <li><a href="/#policy">Vilkår</a></li>
                          <li><a href="https://www.nrk.no/sognogfjordane/vil-du-leige-eit-rusta-vrak_-1.10920467" style="color: white"> NRK Artikkel</a></li>
                      </ul>
                  </div>
              </div>
          </div>
        </div>
    </footer>
    <!--
    <footer class="footer">
        <div class="navbar-static-bottom">
          <div class="container">
              <h3>Konktakt</h3>
              <p>Epost: Rusta</p>
            <p class="">Place sticky footer content here.</p>
          </div>
        </div>

    </footer>
    -->
    <!-- /.container -->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins)
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        -->
    <script src="{% static "packages/JQuery/external/jquery/jquery.js" %}"></script>
     <script src="{% static "packages/JQuery/jquery-ui.min.js" %}"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <script src="{% static "packages/fullcalendar/lib/moment.min.js" %}"></script>
    <script src="{% static "packages/fullcalendar/fullcalendar.js" %}"></script>
    <script src="{% static "packages/fullcalendar/locale/nb.js" %}"></script>
    {% block testBlock %}

    {% endblock testBlock %}

    {% block siteSpesificJs %}

    {% endblock siteSpesificJs %}
  </body>
</html>

rustavrak/templates/contact.html
{% extends 'base.html' %}


{% block Content %}


{% endblock Content %}