cars/urls.py
from django.conf.urls import url
from . import views

app_name = 'cars'
urlpatterns = [
    url(r'^biler/$', views.car_list, name='car_list'),
    url(r'^bil/(?P<car_id>[0-9]+)/$', views.specific_car, name='car_availability'),
]

control_panel/urls.py
from django.conf.urls import url
from . import views

app_name = 'control_panel'
urlpatterns = [
    # Index
    url(r'^$', views.index_control_panel, name='control_panel_index'),

    # No Business dates url: /control_panel/no_reservations
    url(r'^lock_reservations', views.reservation_locks, name='lock_reservations')
]

rustavrak/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns

from frontpage.views import index
urlpatterns = [
    url(r'^$', index),
    url(r'^', include('cars.urls', namespace='cars')),
    url(r'^', include('booking.urls')),
    url(r'^control_panel/', include('control_panel.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

control_panel/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf import settings
from django.db import models

# Create your models here.


# Field to ble able to add a period where there is no business.
# I.e vacation, no time available etc. etc.
class lock_reservation_period(models.Model):
    from_date = models.DateField('Startdato for stopp av bestilling')
    to_date = models.DateField('Sluttdato for stopp av bestilling (T.o.m denne dato)')

    created = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL)

    def __str__(self):
        return "Fra " + str(self.from_date) + " til " + str(self.to_date)


    class Meta:
        verbose_name = 'Låst Periode'
        verbose_name_plural = 'Låste Perioder'


class lock_init_final_dates(models.Model):
    from_date = models.DateField('Startdato for stopp av hente/levering periode')
    to_date = models.DateField('Sluttdato for stopp av hente/levering periode')

    created = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL)

    def __str__(self):
        return "Fra " + str(self.from_date) + " til " + str(self.to_date)


    class Meta:
        verbose_name = 'Låst hente/leverings periode'
        verbose_name_plural = 'Låste hente/leverings perioder'

control_panel/forms.py
    # -*- coding: utf-8 -*-
from django import forms
import datetime



DATE_INPUT_FORMATS = [
    '%d.%m.%Y', # '12.02.2017'
    '%d/%m/%Y', #'12/02/2006'
]


class LockReservationsForm(forms.Form):
    #Essential information for the Booking.
    from_date = forms.DateField(input_formats=DATE_INPUT_FORMATS)
    to_date = forms.DateField(input_formats=DATE_INPUT_FORMATS)

control_panel/views.py
from django.shortcuts import render


from django.contrib.auth.decorators import user_passes_test

from forms import LockReservationsForm
from models import lock_reservation_period
import datetime

@user_passes_test(lambda u: u.is_staff)
def index_control_panel(request):
    return render(request, 'control_panel/index_control_panel.html')



@user_passes_test(lambda u: u.is_staff)
def reservation_locks(request):

    # Standard Return function
    def lock_reservation_page():
        # Get all reservation locks.
        # Except the ones with dates in the past.

        existing_reservation_locks = lock_reservation_period.objects.filter(to_date__gte=datetime.date.today())

        return render(
            request,
            'control_panel/lock_reservation_period.html',
            {'existing_reservation_locks': existing_reservation_locks}
        )

    # POST REQUEST
    if request.method == 'POST':
        form = LockReservationsForm(request.POST)

        # If the form contains two valid dates.
        if form.is_valid():
            posted_from_date = form.cleaned_data['from_date']
            posted_to_date = form.cleaned_data['to_date']

            # If the dates are in the wrong order, reorder.
            if posted_from_date > posted_to_date:
                placeholder = posted_from_date
                from_date = posted_to_date
                posted_to_date = placeholder



            new_lock = lock_reservation_period(
                creator=request.user,
                from_date=posted_from_date,
                to_date=posted_to_date
            )

            new_lock.save()

            return lock_reservation_page()

        else:
            return lock_reservation_page()

    # GET REQUEST
    else:
        return lock_reservation_page()

control_panel/templates/control_panel/index_control_panel.html
{% extends 'base.html' %}

{% block Content %}
<h1>VIP only.</h1>
<hr>
<h3>Sett av datoer</h3>
    <p> Her er det mulig å sette av et rom mellom 2 dato for å stoppe bestillinger på nettsiden. For kunder vil dette se ut som bilene er booket.</p>
    <p>Problemer: Dersom en bestilling allerede eksisterers, må dette håndteres manuelt. Kontakt Kunde eller noe slikt..</p>
    <a href="{% url 'control_panel:lock_reservations'  %}">Stopp booking mellom 2 dato</a>

{% endblock Content %}

control_panel/templates/control_panel/lock_reservation_period.html
{% extends 'base.html' %}


{% block Content %}
<h1>Legg til periode for stopp av reservasjoner</h1>
                <form method="post">{% csrf_token %}
                <div class="row">
                    <div class="col-md-3 col-sm-6 col-xs-12 form-group has-feedback">
                        <label for="from_date" class="control-label date-label">Fra Dato</label>
                        <input type="text" value='' class="form-control datefield" id="from_date" name="from_date">
                        <span class="glyphicon glyphicon-calendar form-control-feedback date_icon" ></span>
                    </div>
                    <div class="col-md-3 col-sm-6 col-xs-12 form-group has-feedback">
                        <label for="to_date" class="control-label date-label">Til date</label>
                        <input type="text" value='' class="form-control datefield" id="to_date" name="to_date">
                        <span class="glyphicon glyphicon-calendar form-control-feedback date_icon" ></span>
                    </div>

                    <div class="col-md-12 col-sm-12 col-xs-12">
                        {% if error %}
                            <div class="alert alert-danger" role="alert">
                                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                                <span class="sr-only">Error:</span>
                                {{ message }}</div>
                        {% endif %}
                    </div>

                </div>

                <div class="row">
                    <div class="col-md-12 col-sm-6 col-xs-12">
                        <button type="submit" id="search_button" class="btn btn-lg"><i class="fa fa-search" aria-hidden="true"></i> Add</button>
                    </div>

                </div>


            </form>



    <hr>

    {% for a in existing_reservation_locks %}
        <p>Fra {{ a.from_date }} til {{ a.to_date }}</p>
    {% endfor %}
{% endblock Content %}


{% block siteSpesificJs %}
<script>

var dp_start_date = $("#from_date");
var dp_end_date = $("#to_date");

dp_end_date.datepicker({
    minDate: 0
});

dp_start_date.datepicker({
    minDate: 0
    });

</script>
{% endblock siteSpesificJs %}